---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-mysql-no-tls
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-mysql-no-tls
  template:
    metadata:
      labels:
        app: vault-mysql-no-tls
    spec:
      serviceAccountName: vault-mysql-no-tls
      containers:
        - name: vault-mysql-no-tls
          image: yanhan/vault-mysql-no-tls:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
            successThreshold: 1
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
            successThreshold: 2
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: vault-mysql-no-tls
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: vault-mysql-no-tls
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vault-mysql-no-tls
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: vault-mysql-no-tls
  namespace: default
spec:
  type: NodePort
  selector:
    app: vault-mysql-no-tls
  ports:
    - name: http
      port: 80
      targetPort: http
