apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kube-state-metrics
spec:
  allowPrivilegeEscalation: false
  allowedCapabilities: []
  defaultAddCapabilities: []
  defaultAllowPrivilegeEscalation: false
  fsGroup:
    ranges:
      - min: 1
        max: 65535
    rule: MustRunAs
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  runAsGroup:
    ranges:
      - min: 1
        max: 65535
    rule: MustRunAs
  runAsUser:
    ranges:
      - min: 1
        max: 65535
    rule: MustRunAs
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
      - min: 1
        max: 65535
    rule: MustRunAs
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - projected
    - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-state-metrics-use-own-psp
  namespace: kube-system
rules:
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["kube-state-metrics"]
    verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-state-metrics-use-own-psp
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-state-metrics-use-own-psp
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: kube-state-metrics
    namespace: kube-system
