apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: blackhole
      #receiver: 'sysdig-test'
    receivers:
      - name: blackhole
      - name: 'sysdig-test'
        webhook_configs:
          - url: 'https://webhook.site/e75bab93-146f-4567-87a4-f7a5b0df1f78' 
