apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eniconfigs.crd.k8s.amazonaws.com
spec:
  conversion:
    strategy: None
  group: crd.k8s.amazonaws.com
  names:
    kind: ENIConfig
    listKind: ENIConfigList
    plural: eniconfigs
    singular: eniconfig
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
