apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: prometheus
data:
  prometheus.rules.yml: |
    groups:
      - name: example
        rules:
          - record: job_service:rpc_durations_seconds_count:avg_rate5m
            expr: avg(rate(rpc_durations_seconds_count[6m])) by (job, service)

  prometheus.yml: |
    global:
      scrape_interval: 15s
      # Attach these labels to any time series or alerts when communicating with
      # external systems (federation, remote storage, Alertmanager).
      external_labels:
        monitor: "foobar"

    rule_files:
      - "prometheus.rules.yml"

    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: "prometheus"
        # Override the global default and scrape targets from this job every 5 seconds.
        scrape_interval: 5s
        static_configs:
          - targets: ["127.0.0.1:9090"]

      - job_name: "node_exporter"
        static_configs:
          - targets: ["prometheus-node-exporter.kube-system:9100"]

      - job_name: "kube-state-metrics"
        static_configs:
          - targets: ["kube-state-metrics.kube-system:8080"]

      - job_name: "kubernetes-api-servers"
        kubernetes_sd_configs:
          - role: endpoints
            api_server: "https://kubernetes.default.svc.cluster.local"
            tls_config:
              ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: default;kubernetes;https

    #  - job_name: "example-random"
    #    # Override the global default and scrape targets from this job every 5 seconds
    #    scrape_interval: 5s
    #    static_configs:
    #      - targets: ["random-8080:8080", "random-8081:8081"]
    #        labels:
    #          group: "production"
    #      - targets: ["random-8082:8082"]
    #        labels:
    #          groups: "canary"
