apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: prometheus
---
# This needs to be a ClusterRole to access the nonResourceURLs
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: prometheus
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["list", "watch"]
  - nonResourceURLs:
      - /metrics
      - /api/*
    verbs:
      - get
---
# This needs to be a ClusterRoleBinding, otherwise there will be
# permissions error about the service account not being able to list resources
# at the cluster scope, similar to the following:
#
# level=error ts=2019-10-05T11:57:15.950Z caller=klog.go:94 component=k8s_client_runtime func=ErrorDepth msg="/app/discovery/kubernetes/kubernetes.go:263: Failed to list *v1.Endpoints: endpoints is forbidden: User \"system:serviceaccount:prometheus:prometheus\" cannot list resource \"endpoints\" in API group \"\" at the cluster scope"
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: prometheus
  kind: ClusterRole
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: prometheus
    namespace: prometheus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app: prometheus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
        - name: prometheus
          image: prom/prometheus
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: config-volume
              mountPath: /etc/prometheus/prometheus.rules.yml
              subPath: prometheus.rules.yml
          ports:
            - name: prom-port
              containerPort: 9090
      volumes:
        - name: config-volume
          configMap:
            name: prometheus
---
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - name: promui
      protocol: TCP
      port: 9090
      targetPort: prom-port
