---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  # Cascading delete
  # https://argo-cd.readthedocs.io/en/stable/user-guide/app_deletion/
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    path: guestbook
  syncPolicy:
    # Adding this will auto sync upon creating the app
    # Otherwise manual sync will be required
    automated: {}
