apiVersion: apps/v1
kind: Deployment
metadata:
  name: tls-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tls-redis
  template:
    metadata:
      labels:
        app: tls-redis
    spec:
      containers:
        - name: main
          image: yanhan/tls-redis:0.1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: REDIS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: tls-redis
                  key: REDIS_ENDPOINT
            - name: REDIS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tls-redis
                  key: REDIS_AUTH_TOKEN
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 2
            failureThreshold: 3
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: tls-redis
  namespace: default
spec:
  type: NodePort
  selector:
    app: tls-redis
  ports:
    - name: http
      port: 80
      targetPort: http
