apiVersion: apps/v1
kind: Deployment
metadata:
  name: tls-redis-nodejs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tls-redis-nodejs
  template:
    metadata:
      labels:
        app: tls-redis-nodejs
    spec:
      containers:
        - name: web
          image: yanhan/tls-redis-nodejs:0.2
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: tls-redis-nodejs
                  key: REDIS_HOST
            - name: REDIS_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: tls-redis-nodejs
                  key: REDIS_AUTH_TOKEN
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: tls-redis-nodejs
  namespace: default
spec:
  type: NodePort
  selector:
    app: tls-redis-nodejs
  ports:
    - name: http
      port: 80
      targetPort: http
