apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: metrics-server
spec:
  allowPrivilegeEscalation: false
  allowedCapabilities:
    - NET_BIND_SERVICE
  defaultAllowPrivilegeEscalation: false
  fsGroup:
    ranges:
      - min: 1
        max: 65535
    rule: MustRunAs
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  requiredDropCapabilities:
    - AUDIT_WRITE
    - CHOWN
    - FOWNER
    - FSETID
    - KILL
    - MKNOD
    - NET_RAW
    - SETFCAP
    - SETGID
    - SETPCAP
    - SETUID
    - SYS_CHROOT
  runAsGroup:
    ranges:
      - min: 1
        max: 65535
    rule: MustRunAs
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
      - min: 1
        max: 65535
    rule: MustRunAs
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - projected
    - secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-server-use-own-psp
  namespace: kube-system
rules:
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["metrics-server"]
    verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-server-use-own-psp
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics-server-use-own-psp
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: metrics-server
    namespace: kube-system
