---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-otlp-xray
  namespace: default
spec:
  replicas: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - go-otlp-xray
  template:
    metadata:
      labels:
        app: go-otlp-xray
    spec:
      containers:
        - name: web
          image: yanhan/go-otlp-xray:v0.2.12
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8831
              protocol: TCP
          env:
            - name: OTLP_COLLECTOR_HOST_PORT
              value: my-collector-xray-collector.default.svc.cluster.local:4317
          readinessProbe:
            httpGet:
              path: /healthz
              port: web
            initialDelaySeconds: 3
            successThreshold: 2
            failureThreshold: 3
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: go-otlp-xray
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: go-otlp-xray
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
